Added ingress docs
run-x/opta-docs pull request #91
Opened 2021-11-03 18:38 UTC by bigbitbus

For the ability of adding arbitrary ingress annotations.

2021-11-05 18:36 UTC, NitinAgg approved these changes

2021-11-05 18:37 UTC, NitinAgg requested changes
Oh this would need to be updated to not use the broad annotations field

2021-11-05 21:11 UTC, bigbitbus commented
> Oh this would need to be updated to not use the broad annotations field

Made changes as per your suggestion.

2021-11-08 19:00 UTC, NitinAgg approved these changes

2021-11-08 19:38 UTC, merged